### PR TITLE
syncdb() has been removed from Django 1.9, use migrate instead

### PR DESCRIPTION
**Pull request by MridulS**

### CODE REVIEW

**Comment by DSin52** [comment]
Thank you so much for your help!

**Comment by tmmurali** [comment]
Divit, how will this work if a user has an older version of Django?
   Murali

**Comment by DSin52** [comment]
This script uses syncdb() for older versions of Django (< 1.7) and migrate for newer versions of Django.

**Comment by tmmurali** [comment]
Oh, yes! I see it in the code. Thanks.
   Murali

**Pull request merged**
