### PR TITLE
#332 - Add a `getting started` documentation for RESTful APIs - Fixes

### PR DESCRIPTION
**Pull request by sanket0211**
Sir, 
I have created the document which describes how to use REST APIs using Postman Application. I have taken inspiration from @sandeepm96 blog  https://summerofcode17.wordpress.com/2017/05/30/using-the-graphspace-restful-api/

Thank you.

### CODE REVIEW

**Comment by tmmurali** [comment]
Thanks for adding this documentation. @sanket0211 please add the following line after the first section heading:

This documentation is based on Sandeep Mahapatra's blog post in the 2017 GSoC and hyperlink "blog post" to the actual blog post. That way, we explicitly give him credit.

**Comment by sanket0211** [comment]
Prof. @tmmurali,
Yes Sir, you are right. I have made the required changes to the doc. 

Thank you.

**Comment by tmmurali** [comment]
Thanks!

**Comment by adbharadwaj** [comment]
👍 Looks good to me

Fixes #356

**Comment by adbharadwaj** [comment]
Can you send the pull request to develop branch instead of master?

**Comment by sanket0211** [comment]
Done. 
Thank you :)

**Comment by adbharadwaj** [comment]
👍

**Pull request merged**
