### PR TITLE
Allow int, float nodes as source and target nodes

### PR DESCRIPTION
**Pull request by MridulS**
TODO: documentation and testing
@tmmurali @DSin52 
https://github.com/Murali-group/GraphSpace/issues/124

### CODE REVIEW

**Comment by DSin52** [comment]
Thank you for your contribution!

**Comment by tmmurali** [comment]
Are there any other types that we might be inadvertently accepting due to
the conversion of the ids to string?
   Murali

**Comment by MridulS** [comment]
This will cast everything as a string be it `int`, `float` ,`string`, `class`, `list`. This won't be a security problem, string can't be executed.

We can add a check so only `int`, `float`, `strings` are accepted.

**Comment by MridulS** [comment]
https://github.com/Murali-group/GraphSpace/pull/135

**Comment by tmmurali** [comment]
Thanks. I like the restriction to these three types.

**Pull request merged**
