### PR TITLE
Check if source and target node exist in JSON node list

### PR DESCRIPTION
**Pull request by MridulS**
https://github.com/Murali-group/GraphSpace/issues/134

### CODE REVIEW

**Comment by tmmurali** [comment]
@MridulS, the list comprehension to build node_list in validate_edge_properties takes O(n) time, where n is the number of nodes. That much time seems wasteful when you only need to check if two nodes are in the graph or not. Is there any way to make the code more efficient?

**Comment by MridulS** [comment]
We need to check this for all edges in the graph hence we may require all the nodes.

The structure of `nodes` forces us to iterate through it once as every node id is inside a dict element and to access all the `id`s it will take O(n).

Will look for more efficient way :)

**Comment by tmmurali** [comment]
Can you build node_list at the very beginning of the validator and pass it
to every edge validation function?

**Comment by MridulS** [comment]
The list is built only once as `validate_edge_properties` function checks for all the edges and the iteration of edges is after the list comprehension.

**Comment by tmmurali** [comment]
Oh, ok. I misunderstood the code.

**Pull request merged**
